[package]
name = "nodetunnel"
version = "0.1.0"
edition = "2024"

[lib]
name = "nodetunnel"
crate-type = ["cdylib"]

[dependencies]
godot = "0.4.2"
renet = "1.2.0"
renet_netcode = "1.2.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
